### ISSUE TITLE
IP address sometimes wrong?

### ISSUE THREAD

**Issue by solomongrundy6** [mjwhitta/sysinfo#1]
I was trying out arTTY, and noticed that the IP address reported is sometimes wrong.  About two thirds of the time, the IP address it reports is my local network LAN address, and only the other third of the time is my outward-facing global IP address. I use a VPN if that's relevant - when I run it while not using the VPN I only get my local LAN address and never the global one.

**Comment by mjwhitta** [comment]
Yes, I've seen this. I wasn't really sure how to handle it as users could have any number of interfaces.

I was just taking the first non-loopback, non-docker IP, but since the array wasn't sorted, it appears random-ish. I have a test version now that will grab the first IP for all non-loopback, non-docker interfaces.

I will push a fix here shortly, and then it will show up in ArTTY a bit later.
